/* 🤖 this file was generated by svg-to-ts*/
export * from './build/icon-alarm.icon';
export * from './build/icon-chat.icon';
export * from './build/icon-dashboard.icon';
export * from './build/icon-email.icon';
export * from './build/icon-thunderbolt.icon';
export * from './build/icon.model';
